### ISSUE TITLE
Sur Symfony 3 : "Notice: Undefined index: client"

### ISSUE THREAD

**Issue by proximiteclient** [rollincode/RCPaiementCMCICBundle#10]
Bonjour, je tente d'installer et d'utiliser le bundle sur un projet symfony 3.

J'ai ce message d'erreur : "Notice: Undefined index: client"

Une idée du pourquoi ?

Merci,

**Comment by nicovak** [comment]
Comme le précise la description et le readme, ce projet est un bundle pour Symfony 2 à l'origine. Je n'ai jamais fais de portage ou de test sur Symfony 3.

**Comment by proximiteclient** [comment]
Dommage... Je pense que ça aiderait de nombreuses autres personnes. Pas d'alternatives connues pour SF 3 ?

**Comment by nicovak** [comment]
Le portage sur Symfony 3 ne doit pas être bien compliqué. Je pense que le plus gros du taf est d'adapter les fichiers de configuration du bundle (https://github.com/rollincode/RCPaiementCMCICBundle/search?utf8=%E2%9C%93&q=client&type=)

https://github.com/rollincode/RCPaiementCMCICBundle/blob/053d8d518b5faa78f58eacf5811ac052e6a9edfb/DependencyInjection/RCPaiementCMCICExtension.php
https://github.com/rollincode/RCPaiementCMCICBundle/blob/053d8d518b5faa78f58eacf5811ac052e6a9edfb/DependencyInjection/Configuration.php

N'utilisant plus Symfony sur mes projets cette évolution n'est pas une priorité. Je suis bien sûr preneur si quelqu'un propose un pull request.

**Comment by proximiteclient** [comment]
J'ai réussi à faire fonctionner.
Donc les parametres à mettre dans config.yml

Nouveau contenu PaiementType.php:
`
namespace RC\PaiementCMCICBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaiementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('version', HiddenType::class)
            ->add('TPE', HiddenType::class)
            ->add('date', HiddenType::class)
            ->add('montant', HiddenType::class)
            ->add('reference', HiddenType::class)
            ->add('MAC', HiddenType::class)
            ->add('url_retour', HiddenType::class)
            ->add('url_retour_ok', HiddenType::class)
            ->add('url_retour_err', HiddenType::class)
            ->add('lgue', HiddenType::class)
            ->add('societe', HiddenType::class)
            ->add('mail', HiddenType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'RC\PaiementCMCICBundle\Entity\Paiement',
        ));
    }

    public function getName()
    {
        return '';
    }
}`

Pour le SamplePaiementController.php au niveau de la création du formulaire de paiement :
`$form = $this->get('form.factory')->createNamed(null,
            PaiementType::class,
            $paiement,
            array(
                'method' => 'POST',
                'action' => $servicePaiement->getUrlPaiement(),
            )
        );`

**Comment by matthv** [comment]
Bonjour,

Dans les forks il y a un utilisateur qui a visiblement fait évolué le bundle.
https://github.com/Azimut56/RCPaiementCMCICBundle

**Comment by proximiteclient** [comment]
@nicovak tu as moyen de puller dans ton repo ?

**Comment by matthv** [comment]
Mais non @proximiteclient, utilise ce fork pour régler ton soucis 😉. Tu le précises dans ton composer.

**Comment by proximiteclient** [comment]
@matthv comment faire en sorte que composer le comprenne ? Merci.

**Comment by nicovak** [comment]
https://snippets.khromov.se/composer-use-your-own-fork-for-a-package/

**Comment by xorgxx** [comment]
Bonjour, le forks de "Azimut56" fonctionne de la mème façon sous Sf3.xx ? 
utilise ce bundle dans une version Sf2.8 (sans problème). Je suis passé en Sf3.xx. il y a t'il des problèmes?

Merci
