### ISSUE TITLE
CGI2 not ok

### ISSUE THREAD

**Issue by proximiteclient** [rollincode/RCPaiementCMCICBundle#11]
Bonjour

Tout fonctionne bien sur SF3 à présent, en faisant un test en mode test, la CGI2 est bien appelée car les actions suite au code retour sont bien effectuée.
Par contre ca m'affiche CGI2 not ok dans le debug.

Une idée ?

**Comment by nicovak** [comment]
Je crois que c'est l'URL de retour, vérifies le depuis l'interface commerçant.

**Comment by matthv** [comment]
C'est dans la doc technique.

Que faire lorsque je rencontre une erreur « CGI2 NOT OK » ?
Vous devez tout d’abord effectuer les vérifications de base suivantes :
 L’adresse de l’interface « Retour » que vous nous avez fournie est-elle valide ?
 Cette adresse est-elle accessible sur votre serveur depuis l’extérieur ?
 Le port sur lequel s’adresser à votre interface « Retour » est-il bien 80 (http) ou 443
(https) ? En effet, notre serveur de paiement n’accepte de s’adresser qu’à ces deux ports
Si le problème persiste, veuillez effectuer les vérifications supplémentaires suivantes :
 le traitement entre le retour de notre serveur et votre envoi d'accusé de réception ne doit
pas durer trop longtemps (moins de 30 secondes)
 il ne doit pas être fait de redirection à la réception du code retour paiement
 Le format de l’accusé de réception renvoyé doit correspondre au format attendu pour un
sceau valide.

**Comment by proximiteclient** [comment]
J'ai fait toutes ces vérif déjà....
J'ai fourni cette url : https://domaine.fr/paiement/verification
Elle attend des paramètres de retour en GET ou POST. Par contre quand j'y accède directement sans variables j'ai une erreur 500, est ce pour ça ? J'ai pourant pris le code sample du Bundle.

Merci à vous;,

**Comment by nicovak** [comment]
Tu as fait les url de retours après paiement ? Dans le Sample c'est là:

```
    /**
     *
     * @Route(path="/paiement/retour/{status}", name="paiement-retour", requirements={
     * "status" : "success|error"
     * })
     * @param $status
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function paiementRetourAction($status = null)
    {
        return $this->render('RCPaiementCMCICBundle:Paiement:retour.html.twig', array(
            'status' => $status
        ));
    }
```

Donc tu auras 
- https://domaine.fr/paiement/retour/success
- https://domaine.fr/paiement/retour/error

https://domaine.fr/paiement/verification c'est l'URL que les serveur de paiement vont interroger en off une fois que le paiement est validé par la banque.

**Comment by proximiteclient** [comment]
Oui tout à fait.
