### ISSUE TITLE
Fork de "lhadot"

### ISSUE THREAD

**Issue by xorgxx** [rollincode/RCPaiementCMCICBundle#13]
Bonjour je viens installer le bundle fork de "lhadot". Pourquoi le paramètre ALGO? puis pourquoi ne pas mettre une valeur pas défaut? (le Cm propose que 2 - MD5, SHA1) 

j'ai vu qu'une ```référence``` est mise pas défaut a la creation de ``` ->getPaiementObjet```, d’où ma question comment la gérer en ```retour serveur``` ?

Merci.

**Comment by matthv** [comment]
Bonjour, pourquoi ne pas demander à l'auteur du Fork directement sur son Repo ? 

[https://github.com/lhadot/RCPaiementCMCICBundle/](https://github.com/lhadot/RCPaiementCMCICBundle/)

**Comment by xorgxx** [comment]
Tres bonne ```response``` !! mais voila comment?

**Comment by matthv** [comment]
Demander à l'auteur d'activer les issues sur son dépot
[https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork](https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork)

Pour le contacter il suffit de passer par son email (sans trop spammer l'auteur)

`git clone https://github.com/lhadot/RCPaiementCMCICBundle/`
`cd RCPaiementCMCICBundle`
`git log`

Regarder dans les derniers commits il y a l'email de l'auteur.

**Comment by xorgxx** [comment]
Ok merci. 
En tous les cas merci pour le job !!
