### ISSUE TITLE
- "compte certaines précautions" -

### ISSUE THREAD

**Issue by xorgxx** [rollincode/RCPaiementCMCICBundle#4]
Bonjour, je dois coder un système de payement avec Credit Mutuel ( monetico ).
Quelles sont les précautions ?

Merci.

**Comment by nicovak** [comment]
Bonjour,

La partie communication entre l'appli et le serveur est sécurisée via la clé secrète donc pas de soucis de ce coté là. Après comme expliqué dans le readme, il faut effectuer la logique de paiement uniquement au retour de la plateforme de paiement (url de retour) via le service (commande validé, erreur de paiement etc, https://github.com/rollincode/RCPaiementCMCICBundle/blob/master/Services/SampleLogicTpeService.php)
Il ne faut surtout pas valider une commande en dehors de ce contexte.

Si mes souvenirs sont bons, on peut aussi restreindre l'IP qui appelle le service de paiement depuis l'interface commerçant.

Dans le bundle il y a plusieurs fichier d'exemple (controller et services) sur lesquels il faut s'appuyer.

Je te conseil aussi de voir du coté de la doc technique de monetico. Pour info, ce bundle s’appuie sur celui de paybox. (une plateforme similaire à monetico, il y a juste le visuel de l'interface commerçant qui change, la logique est la même https://github.com/lexik/LexikPayboxBundle).

Bon courage

**Comment by xorgxx** [comment]
La bonne nouvelle c'est que je boss déjà avec LexikPaybox et je dois dire que je suis très très content de ce bundle. Je ne pensais pas pouvoir aussi utiliser pour le système Monetico, j'avais bien vu des caractéristiques similaires. Donc je vais essayer dans un premier temps avec LexikPaybox (j'ai déjà toutes les logiques).

Merci pour ta réponse aussi rapide et de ton aide.
