### ISSUE TITLE
SF2.8.26 [InvalidArgumentException] 

### ISSUE THREAD

**Issue by dedioweb** [rollincode/RCPaiementCMCICBundle#8]
Hello, 
Je suis sous SF 2.8.26, essayant la commande composer  : 

composer require rollincode/paiementcmcic-bundle

J'obtiens du terminal l'erreur suivante : 
  [InvalidArgumentException]                                                                                                                                       
  Could not find package rollincode/paiementcmcic-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Quelqu'un peut me dire pourquoi ? 
Par avance, merci

**Comment by nicovak** [comment]
Essais de changer le minimum stability dans le composer.json
https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by dedioweb** [comment]
@nicovak 
Je n'avais pas de minimum stability dans mon composer.json, 
J'ai ajouté "minimum-stability": "dev",
ensuite en exécutant la commande : $ php composer require rollincode/paiementcmcic-bundle

j'obtiens : 

Using version dev-master for rollincode/paiementcmcic-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 32 bytes) in phar:///Users/dedioweb/Sites/e328/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

**Comment by nicovak** [comment]
Ca vient de la config PHP, essais d'allouer plus de mémoire dans le php.ini

**Comment by dedioweb** [comment]
@nicovak 
J'ai donc mis dans composer.json : 
"minimum-stability": "dev",
J'ai changé la mémoire php.ini
et ça a fonctionné, merci
